version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: jobportal-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: jobportal-redis
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: jobportal-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: jobportal-kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobportal-web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      ELASTICSEARCH_DSL_HOSTS: ${ELASTICSEARCH_HOST}

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobportal-celery
    command: celery -A job_portal worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - elasticsearch
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      ELASTICSEARCH_DSL_HOSTS: ${ELASTICSEARCH_HOST}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

  nginx:
    image: nginx:stable
    container_name: jobportal-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  postgres_data:
  es_data:
