version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: jobportal-db
    restart: always
    environment:
      POSTGRES_DB: jobportal
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: jobportal-redis
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobportal-web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_DB: jobportal
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobportal-celery
    command: celery -A job_portal worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      POSTGRES_DB: jobportal
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  nginx:
    image: nginx:stable
    container_name: jobportal-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  postgres_data:
